//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("purchase-order", Namespace="", IsNullable=false)]
public partial class PurchaseOrder {
    
    private uint ponumberField;
    
    private System.DateTime podateField;
    
    private System.DateTime potimeField;
    
    private System.DateTime expectedshipdateField;
    
    private purchaseorderShippingdetail shippingdetailField;
    
    private string customernameField;
    
    private purchaseorderPoline[] polineField;
    
    private decimal ordersubtotalField;
    
    private decimal salestaxField;
    
    private decimal shippingfeesField;
    
    private decimal ordertotalField;
    
    private string postatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public uint ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-date", DataType="date")]
    public System.DateTime podate {
        get {
            return this.podateField;
        }
        set {
            this.podateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-time", DataType="time")]
    public System.DateTime potime {
        get {
            return this.potimeField;
        }
        set {
            this.potimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-ship-date", DataType="date")]
    public System.DateTime expectedshipdate {
        get {
            return this.expectedshipdateField;
        }
        set {
            this.expectedshipdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-detail")]
    public purchaseorderShippingdetail shippingdetail {
        get {
            return this.shippingdetailField;
        }
        set {
            this.shippingdetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-name")]
    public string customername {
        get {
            return this.customernameField;
        }
        set {
            this.customernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line")]
    public purchaseorderPoline[] poline {
        get {
            return this.polineField;
        }
        set {
            this.polineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-subtotal")]
    public decimal ordersubtotal {
        get {
            return this.ordersubtotalField;
        }
        set {
            this.ordersubtotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sales-tax")]
    public decimal salestax {
        get {
            return this.salestaxField;
        }
        set {
            this.salestaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-fees")]
    public decimal shippingfees {
        get {
            return this.shippingfeesField;
        }
        set {
            this.shippingfeesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-total")]
    public decimal ordertotal {
        get {
            return this.ordertotalField;
        }
        set {
            this.ordertotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-status")]
    public string postatus {
        get {
            return this.postatusField;
        }
        set {
            this.postatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderShippingdetail {
    
    private string shiptonameField;
    
    private string addressField;
    
    private string cityField;
    
    private string stateField;
    
    private ushort zipcodeField;
    
    private ulong phoneField;
    
    private string shippingmethodField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ship-to-name")]
    public string shiptoname {
        get {
            return this.shiptonameField;
        }
        set {
            this.shiptonameField = value;
        }
    }
    
    /// <remarks/>
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ushort zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }
    
    /// <remarks/>
    public ulong phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-method")]
    public string shippingmethod {
        get {
            return this.shippingmethodField;
        }
        set {
            this.shippingmethodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPoline {
    
    private purchaseorderPolinePolineheader polineheaderField;
    
    private purchaseorderPolinePolinedetail polinedetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-header")]
    public purchaseorderPolinePolineheader polineheader {
        get {
            return this.polineheaderField;
        }
        set {
            this.polineheaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-detail")]
    public purchaseorderPolinePolinedetail polinedetail {
        get {
            return this.polinedetailField;
        }
        set {
            this.polinedetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPolinePolineheader {
    
    private byte linenumberField;
    
    private uint itemidField;
    
    private string itemnameField;
    
    private object handlinginstructionsField;
    
    private object handlingindField;
    
    private decimal itemsellpriceField;
    
    private byte orderquantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line-number")]
    public byte linenumber {
        get {
            return this.linenumberField;
        }
        set {
            this.linenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-id")]
    public uint itemid {
        get {
            return this.itemidField;
        }
        set {
            this.itemidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-name")]
    public string itemname {
        get {
            return this.itemnameField;
        }
        set {
            this.itemnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handling-instructions")]
    public object handlinginstructions {
        get {
            return this.handlinginstructionsField;
        }
        set {
            this.handlinginstructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handling-ind")]
    public object handlingind {
        get {
            return this.handlingindField;
        }
        set {
            this.handlingindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-sell-price")]
    public decimal itemsellprice {
        get {
            return this.itemsellpriceField;
        }
        set {
            this.itemsellpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-quantity")]
    public byte orderquantity {
        get {
            return this.orderquantityField;
        }
        set {
            this.orderquantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPolinePolinedetail {
    
    private string polinestatusField;
    
    private byte quantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-status")]
    public string polinestatus {
        get {
            return this.polinestatusField;
        }
        set {
            this.polinestatusField = value;
        }
    }
    
    /// <remarks/>
    public byte quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}
