//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("purchase-order", Namespace="", IsNullable=false)]
public partial class purchaseorder {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ponumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string podate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string potime;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-ship-date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string expectedshipdate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customername;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-subtotal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ordersubtotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sales-tax", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string salestax;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-fees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingfees;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-total", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ordertotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postatus;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public purchaseorderShippingdetail[] shippingdetail;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public purchaseorderPoline[] poline;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderShippingdetail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ship-to-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shiptoname;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipcode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phone;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-method", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingmethod;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPoline {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public purchaseorderPolinePolineheader[] polineheader;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public purchaseorderPolinePolinedetail[] polinedetail;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPolinePolineheader {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linenumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemid;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemname;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handling-instructions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string handlinginstructions;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handling-ind", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string handlingind;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-sell-price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemsellprice;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderquantity;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseorderPolinePolinedetail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-line-status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string polinestatus;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string quantity;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("purchase-order")]
    public purchaseorder[] Items;
}
