//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
[System.Xml.Serialization.XmlRootAttribute("shipment-feed", Namespace="http://seller.marketplace.sears.com/oms/v5", IsNullable=false)]
public partial class ShipmentFeed {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime deprecated;
    
    /// <remarks/>
    public shipmentfeedShipment shipment;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipment {
    
    /// <remarks/>
    public shipmentfeedShipmentHeader header;
    
    /// <remarks/>
    public shipmentfeedShipmentDetail detail;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentHeader {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("asn-number")]
    public uint asnnumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public uint ponumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-date", DataType="date")]
    public System.DateTime podate;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentDetail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracking-number", DataType="integer")]
    public string trackingnumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ship-date", DataType="date")]
    public System.DateTime shipdate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-carrier")]
    public string shippingcarrier;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-method")]
    public string shippingmethod;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("package-detail")]
    public shipmentfeedShipmentDetailPackagedetail[] packagedetail;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentDetailPackagedetail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line-number")]
    public byte linenumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-id")]
    public uint itemid;
    
    /// <remarks/>
    public byte quantity;
}
