//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
[System.Xml.Serialization.XmlRootAttribute("shipment-feed", Namespace="http://seller.marketplace.sears.com/oms/v5", IsNullable=false)]
public partial class ShipmentFeed {
    
    private System.DateTime deprecatedField;
    
    private shipmentfeedShipment shipmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime deprecated {
        get {
            return this.deprecatedField;
        }
        set {
            this.deprecatedField = value;
        }
    }
    
    /// <remarks/>
    public shipmentfeedShipment shipment {
        get {
            return this.shipmentField;
        }
        set {
            this.shipmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipment {
    
    private shipmentfeedShipmentHeader headerField;
    
    private shipmentfeedShipmentDetail detailField;
    
    /// <remarks/>
    public shipmentfeedShipmentHeader header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public shipmentfeedShipmentDetail detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentHeader {
    
    private uint asnnumberField;
    
    private uint ponumberField;
    
    private System.DateTime podateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("asn-number")]
    public uint asnnumber {
        get {
            return this.asnnumberField;
        }
        set {
            this.asnnumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-number")]
    public uint ponumber {
        get {
            return this.ponumberField;
        }
        set {
            this.ponumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("po-date", DataType="date")]
    public System.DateTime podate {
        get {
            return this.podateField;
        }
        set {
            this.podateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentDetail {
    
    private string trackingnumberField;
    
    private System.DateTime shipdateField;
    
    private string shippingcarrierField;
    
    private string shippingmethodField;
    
    private shipmentfeedShipmentDetailPackagedetail[] packagedetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracking-number", DataType="integer")]
    public string trackingnumber {
        get {
            return this.trackingnumberField;
        }
        set {
            this.trackingnumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ship-date", DataType="date")]
    public System.DateTime shipdate {
        get {
            return this.shipdateField;
        }
        set {
            this.shipdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-carrier")]
    public string shippingcarrier {
        get {
            return this.shippingcarrierField;
        }
        set {
            this.shippingcarrierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipping-method")]
    public string shippingmethod {
        get {
            return this.shippingmethodField;
        }
        set {
            this.shippingmethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("package-detail")]
    public shipmentfeedShipmentDetailPackagedetail[] packagedetail {
        get {
            return this.packagedetailField;
        }
        set {
            this.packagedetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://seller.marketplace.sears.com/oms/v5")]
public partial class shipmentfeedShipmentDetailPackagedetail {
    
    private byte linenumberField;
    
    private uint itemidField;
    
    private byte quantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line-number")]
    public byte linenumber {
        get {
            return this.linenumberField;
        }
        set {
            this.linenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-id")]
    public uint itemid {
        get {
            return this.itemidField;
        }
        set {
            this.itemidField = value;
        }
    }
    
    /// <remarks/>
    public byte quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}
